name: Release main module

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

env:
  GITHUB_ORG: ${{ github.repository_owner }}
  VERSION_TAG: "1.0.0"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get all repository
        run: |
          ./get-all-repo-release-version ${{ env.GITHUB_ORG }}
          cat Astridstar-release-version.md

      - name: Create a release
        run: |
          cat "version.txt" | while read line || [[ -n $line ]];
          do
              echo "$line"
              if [ "$line" == "null" ]
                then
                  echo "Null version tag"
                  exit
              fi 
          done






