name: Release main module

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

env:
  GITHUB_ORG: ${{ github.repository_owner }}
  VERSION_TAG: "1.0.0"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get all repository
        run: |
          ./get-all-repo-release-version ${{ env.GITHUB_ORG }}
          cat Astridstar-release-version.md

      - name: Create a release
        run: |
          cat "version.txt" | while read line || [[ -n $line ]];
          do
              echo "$line"
              if [ "$line" == "null" ]
                then
                  echo "Null version tag"
                  exit
              fi 
              if [ "$line" ]
                then
                echo "Release version" $line
                git config --global user.email "${{ github.actor }}@example.com"
                git config --global user.name "${{ github.actor }}"
                #git add .
                #git commit -n -m "Updating version list"
                git tag -a $line -m "Release $line"
                git remote remove origin 
                git remote add origin https://${{ github.token }}@github.com/${{ github.repository }}
                git push origin main --tags
                git remote remove origin 
                echo "https://api.github.com/repos/${{ github.repository }}/releases"
                VERSION_TAG=$line
                curl -X POST \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/${{ github.repository }}/releases" \
                  -d '{ "tag_name":"$line", "name": "Release $line is now available", "body": "$( cat Astridstar-release-version.md )" }'                 
              fi
          done






