name: Release main module

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_ORG: ${{ github.repository_owner }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get all repository
        run: |
          ./get-all-repo-release-version ${{ env.GITHUB_ORG }}
          cat Astridstar-release-version.md

          git config --global user.email "${{ github.actor }}@example.com"
          git config --global user.name "${{ github.actor }}"

          git add .
          git commit -m "Updating version list"
          git remote origin set-URL https://${{ github.token }}@github.com/Astridstar/appdeploy



 

