name: Release main module

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_ORG: ${{ github.repository_owner }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get all repository
        run: ./get-all-repo-release-version ${{ env.GITHUB_ORG }}

 

